#### create,list,delete s3 bucket using aws cli and github actions


name: 'AWS S3 bucket'

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  create_list_delete_S3_bucket :
    name: 'S3'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3



    - name: Copy files to the production website with the AWS CLI
      env:
         # set  AWS_ACCESS_KEY_ID ,  AWS_SECRET_ACCESS_KEY , AWS_REGION in github secrets.
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }}
      run : |
        aws s3 mb s3://buck7sept22
	aws s3 ls
	aws s3 ls s3://buck7sept22
	aws s3 rb s3://buck7sept22
  
